
version: '3.7'

services:
  peer0.csjmu.com:
    container_name: peer0.csjmu.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      # Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  peer1.csjmu.com:
    container_name: peer1.csjmu.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      # Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  peer2.csjmu.com:
    container_name: peer2.csjmu.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      # Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  # peer3.csjmu.com:
  #   container_name: peer3.csjmu.com
  #   image: hyperledger/fabric-peer:latest
  #   labels:
  #     service: hyperledger-fabric
  #   environment:
  #     # Generic peer variables
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
  #   volumes:
  #     - ./docker/peercfg:/etc/hyperledger/peercfg
  #     - ${DOCKER_SOCK}:/host/var/run/docker.sock

  # peer4.csjmu.com:
  #   container_name: peer4.csjmu.com
  #   image: hyperledger/fabric-peer:latest
  #   labels:
  #     service: hyperledger-fabric
  #   environment:
  #     # Generic peer variables
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
  #   volumes:
  #     - ./docker/peercfg:/etc/hyperledger/peercfg
  #     - ${DOCKER_SOCK}:/host/var/run/docker.sock
  
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
